{% set name = "free-proxy" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/free_proxy-{{ version }}.tar.gz
  sha256: 6d82aa112e3df7725bdbf177e2110bccdf5f3bbd6e1c70b8616ec12ae3bbf98c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - lxml
    - python >={{ python_min }}
    - requests

test:
  imports:
    - fp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jundymek/free-proxy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Proxy scraper for further use
  doc_url: https://github.com/jundymek/free-proxy
  dev_url: https://github.com/jundymek/free-proxy

extra:
  recipe-maintainers:
    - jan-janssen
    - arunkannawadi
    - jundymek
