{% set name = "free-proxy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/free_proxy-{{ version }}.tar.gz
  sha256: 2b20eb863972b42984292cee17132f4c9ddb8fef0a9bee9bc15215a08e6899fb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - requests

test:
  imports:
    - fp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jundymek/free-proxy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Proxy scraper for further use
  doc_url: https://github.com/jundymek/free-proxy
  dev_url: https://github.com/jundymek/free-proxy

extra:
  recipe-maintainers:
    - jan-janssen
    - arunkannawadi
    - jundymek
